language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install --use-mirrors unittest2; fi
  # - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then git clone git://github.com/mitsuhiko/werkzeug.git; cd werkzeug; pip install --editable . fi

# command to run tests
script: nosetests test.py
