language: python
python:
  - "2.6"
  - "2.7"
  # Taking this out because werkzeug is failing for now.
  # - "3.2"
# command to install dependencies
install:
  - "pip install unittest2"
  - "pip install -r requirements.txt"
# command to run tests
script: nosetests test.py
