language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  # - "3.4"

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install --use-mirrors unittest2; fi

# command to run tests
script: nosetests test.py
